### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by jcorporation** [jcorporation/webradiodb#4]
- [x] Improve performance of index creation
- [x] Workflow for Webradio edit
- [x] Workflow for Webradio delete
- [x] use only first line of json input data for tags
- [x] replace `;` or `,` with `, ` in genre tag
- [x] create list of genres
- [x] create list of languages
- [x] create list of countries
- [x] add genre/country/language filter to search

**Comment by tsunulukai** [comment]
Hello,
Now that you've implemented the search with extra filters, could it be possible to allow searching for an empty string if those filters are selected ?
Eg: be able to query all radio stations from country X in language Y ?

**Comment by tsunulukai** [comment]
Sorting the results by station name / country / language would also be nice :)

**Comment by jcorporation** [comment]
Good proposals!
